import 'dart:io';
import 'package:path_provider/path_provider.dart';

import 'package:share_plus/share_plus.dart';
import '../models/presentation.dart' as model;
import 'security_service.dart';

class ExportService {
  // ===== ЭКСПОРТ В PPTX (REAL POWERPOINT FILE) =====

  static Future<String?> exportToPPTX({
    required model.Presentation presentation,
    required bool isPremium,
  }) async {
    try {
      final directory = await getTemporaryDirectory();
      final safeFileName =
          SecurityService.sanitizeString(presentation.title);

      final fileName =
          '${safeFileName}_${DateTime.now().millisecondsSinceEpoch}.pptx';

      final file = File('${directory.path}/$fileName');

      

      for (final slideData in presentation.slides) {
        final slide = pptx.slides.add();

        // Заголовок
        slide.shapes.addTextBox(
         
          slideData.title,
          left: 40,
          top: 40,
          width: 600,
          height: 60,
        );

        // Подзаголовок
        if (slideData.subtitle != null) {
          slide.shapes.addTextBox(
            TextAnchor.topLeft,
            slideData.subtitle!,
            left: 40,
            top: 110,
            width: 600,
            height: 40,
          );
        }

        // Контент
        double yOffset = 180;

        for (final point in slideData.content) {
          slide.shapes.addTextBox(
            TextAnchor.topLeft,
            '• $point',
            left: 60,
            top: yOffset,
            width: 650,
            height: 30,
          );

          yOffset += 35;
        }

        // Картинка (если есть)
        if (slideData.imageUrl != null) {
          slide.shapes.addTextBox(
            TextAnchor.topLeft,
            '🖼 Image: ${slideData.imageUrl}',
            left: 40,
            top: yOffset + 20,
            width: 650,
            height: 30,
          );
        }
      }

      // ===== СОХРАНЕНИЕ =====
      final bytes = await pptx.save();
      await file.writeAsBytes(bytes);

      pptx.dispose();

      // ===== SHARE =====
      await Share.shareXFiles(
        [XFile(file.path)],
        subject: presentation.title,
      );

      return file.path;
    } catch (e) {
      throw Exception('Ошибка экспорта в PPTX: $e');
    }
  }

  // ===== ЭКСПОРТ В PDF (оставляем как заглушку, без изменений архитектуры) =====

  static Future<String?> exportToPDF({
    required model.Presentation presentation,
    required bool isPremium,
  }) async {
    if (!isPremium) {
      throw Exception('PDF доступен только в Premium версии');
    }

    try {
      final directory = await getTemporaryDirectory();
      final fileName =
          '${presentation.title}_${DateTime.now().millisecondsSinceEpoch}.pdf';

      final file = File('${directory.path}/$fileName');

      await file.writeAsString('PDF EXPORT PLACEHOLDER');

      await Share.shareXFiles([XFile(file.path)], subject: presentation.title);

      return file.path;
    } catch (e) {
      throw Exception('Ошибка экспорта в PDF: $e');
    }
  }

  // ===== SHARE TEXT =====

  static Future<void> shareAsText(model.Presentation presentation) async {
    final buffer = StringBuffer();

    buffer.writeln('📊 ${presentation.title}');
    buffer.writeln('Slides: ${presentation.slides.length}');
    buffer.writeln('Generated by Презентатор ИИ');

    await Share.share(buffer.toString());
  }
}